[package]
name = "echor"
version = "0.1.0"
edition = "2021"

[dependencies]

# https://docs.rs/clap/latest/clap/
clap = "4.5.7"

[dev-dependencies]
anyhow = "1.0.86"
assert_cmd = "2.0.14"
predicates = "3.1.0"
pretty_assertions = "1.4.0"
